# Generated by Django 4.1.3 on 2023-09-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expoBot', '0002_botuser_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.TextField(null=True, verbose_name='ID бота')),
            ],
        ),
    ]
